In [1]:
import pandas as pd
import requests
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [2]:
visits = pd.read_csv('visits_1k.csv')
registrations = pd.read_csv('regs_1k.csv')

In [3]:
visits.head()

,uuid,platform,user_agent,date
0,1de9ea66-70d3-4a1f-8735-df5ef7697fb9,web,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2...,2023-03-01T13:29:22
1,f149f542-e935-4870-9734-6b4501eaf614,web,Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) Apple...,2023-03-01T16:44:28
2,f149f542-e935-4870-9734-6b4501eaf614,web,Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) Apple...,2023-03-06T06:12:36
3,08f0ebd4-950c-4dd9-8e97-b5bdf073eed1,web,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109...,2023-03-01T20:16:37
4,08f0ebd4-950c-4dd9-8e97-b5bdf073eed1,web,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109...,2023-03-05T17:42:47

In [4]:
registrations.head()

,date,user_id,email,platform,registration_type
0,2023-03-01T00:25:39,8838849,joseph95@example.org,web,google
1,2023-03-01T14:53:01,8741065,janetsuarez@example.net,web,yandex
2,2023-03-01T14:27:36,1866654,robert67@example.org,web,google
3,2023-03-01T02:42:34,1577584,elam@example.net,web,apple
4,2023-03-01T10:27:14,4765395,stephanie68@example.net,web,yandex

In [5]:
visits.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   uuid        1000 non-null   str
 1   platform    1000 non-null   str
 2   user_agent  1000 non-null   str
 3   date        1000 non-null   str
dtypes: str(4)
memory usage: 31.4 KB

In [6]:
registrations.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1000 non-null   str
 1   user_id            1000 non-null   int64
 2   email              1000 non-null   str
 3   platform           1000 non-null   str
 4   registration_type  1000 non-null   str
dtypes: int64(1), str(4)
memory usage: 39.2 KB

In [7]:
visits.describe(include='all')

,uuid,platform,user_agent,date
count,1000,1000,1000,1000
unique,519,3,28,996
top,251a0926-ece3-4d77-aa42-ab569fdf9fe2,web,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,2023-03-01T08:01:45
freq,4,954,71,2

In [8]:
registrations.describe(include='all')

,date,user_id,email,platform,registration_type
count,1000,1.000000e+03,1000,1000,1000
unique,1000,NaN,997,3,4
top,2023-03-01T00:25:39,NaN,zanderson@example.org,android,email
freq,1,NaN,2,517,446
mean,NaN,4.488623e+06,NaN,NaN,NaN
std,NaN,2.620568e+06,NaN,NaN,NaN
min,NaN,2.236800e+04,NaN,NaN,NaN
25%,NaN,2.235489e+06,NaN,NaN,NaN
50%,NaN,4.473044e+06,NaN,NaN,NaN
75%,NaN,6.779707e+06,NaN,NaN,NaN
max,NaN,8.881772e+06,NaN,NaN,NaN

In [9]:
visits.isna().sum()

uuid          0
platform      0
user_agent    0
date          0
dtype: int64

In [10]:
registrations.isna().sum()

date                 0
user_id              0
email                0
platform             0
registration_type    0
dtype: int64

In [11]:
visits.duplicated().sum()

np.int64(0)

In [12]:
registrations.duplicated().sum()

np.int64(0)

In [13]:
# Запросы к API

In [14]:
base_url = 'https://data-charts-api.hexlet.app'

begin = '2023-03-01'
end = '2023-09-01'

In [15]:
visits_response = requests.get(
    f'{base_url}/visits',
    params={
        'begin': begin,
        'end': end
    }
)

visits_response.raise_for_status()

In [16]:
registrations_response = requests.get(
    f'{base_url}/registrations',
    params={
        'begin': begin,
        'end': end
    }
)

registrations_response.raise_for_status()

In [17]:
visits_api = pd.DataFrame(visits_response.json())
registrations_api = pd.DataFrame(registrations_response.json())

In [18]:
visits_api.head()

,visit_id,platform,user_agent,datetime
0,60db9b85-12b3-447a-b93d-be177181f732,web,Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7...,2023-04-05T15:03:40
1,9e73a9ba-0c42-4a4d-bf8a-bde5bbe655ed,web,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,2023-04-05T10:59:38
2,9e73a9ba-0c42-4a4d-bf8a-bde5bbe655ed,web,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,2023-04-03T14:53:40
3,16dea4d8-2fb7-4c6b-b953-dc2b9686daf5,web,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,2023-04-05T03:12:36
4,166bc823-c133-41fa-913d-3dbc495b2770,web,Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7...,2023-04-05T11:48:56

In [19]:
registrations_api.head()

,datetime,user_id,email,platform,registration_type
0,2023-03-01T07:40:13,2e0f6bb8-b029-4f45-a786-2b53990d37f1,ebyrd@example.org,web,google
1,2023-03-01T13:14:00,f007f97c-9d8b-48b5-af08-119bb8f6d9b6,knightgerald@example.org,web,email
2,2023-03-01T03:05:50,24ff46ae-32b3-4a74-8f27-7cf0b8f32f15,cherylthompson@example.com,web,apple
3,2023-03-01T00:04:47,3e9914e1-5d73-4c23-b25d-b59a3aeb2b60,halldavid@example.org,web,email
4,2023-03-01T18:31:52,27f875fc-f8ce-4aeb-8722-0ecb283d0760,denise86@example.net,web,google

In [20]:
visits_api.shape, registrations_api.shape

((263459, 4), (21836, 5))

In [21]:
visits_api.info()

<class 'pandas.DataFrame'>
RangeIndex: 263459 entries, 0 to 263458
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   visit_id    263459 non-null  str
 1   platform    263459 non-null  str
 2   user_agent  263459 non-null  str
 3   datetime    263459 non-null  str
dtypes: str(4)
memory usage: 8.0 MB

In [22]:
registrations_api.info()

<class 'pandas.DataFrame'>
RangeIndex: 21836 entries, 0 to 21835
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   datetime           21836 non-null  str
 1   user_id            21836 non-null  str
 2   email              21836 non-null  str
 3   platform           21836 non-null  str
 4   registration_type  21836 non-null  str
dtypes: str(5)
memory usage: 853.1 KB